# Generated by Django 6.0.2 on 2026-02-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_anomaly',
            field=models.BooleanField(default=False, help_text='Flagged by ML as unusual spending'),
        ),
        migrations.AddField(
            model_name='expense',
            name='risk_score',
            field=models.FloatField(default=0.0, help_text='Anomaly confidence/risk score (0 to 1)'),
        ),
    ]
