# Generated by Django 6.0.2 on 2026-02-28 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_is_anomaly_expense_risk_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Used for ML Budget Optimization', max_digits=12)),
                ('city_tier', models.IntegerField(choices=[(1, 'Tier 1 (Metro)'), (2, 'Tier 2 (Urban)'), (3, 'Tier 3 (Semi-Urban/Rural)')], default=2)),
                ('savings_target_range', models.CharField(default='20%-30%', help_text="e.g. '20%-30%'", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
