# Generated by Django 6.0.2 on 2026-03-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='savings_target_range',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='savings_target_percentage',
            field=models.IntegerField(default=20, help_text='e.g. 25 for 25%'),
        ),
    ]
