# Generated by Django 6.0.2 on 2026-03-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_userprofile_savings_target_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Set to True if ML confidence is low < 0.75'),
        ),
    ]
